= Quiz on Chapter 9

* Question 1:
** Explain what is meant by a recursive subroutine.

* 서브루틴 자신을 직접 혹은 간접적으로 호출하는 서브루틴을 의미한다.
---

* Question 2:
** Show the output that would be produced by the subroutine calls `printStuff(0)`, `printStuff(1)`, `printStuff(2)`, and `printStuff(3)`.

[source, java]
----
static void printStuff(int level) {
    if (level == 0) {
       System.out.print("*");
    }
    else {
       System.out.print("[");
       printStuff(level - 1);
       System.out.print(",");
       printStuff(level - 1);
       System.out.print("]");
    }
}
----

0    *
1    [*,*]
2    [[*,*],[*,*]]
3    [[[*,*],[*,*]],[[*,*],[*,*]]]

---

* Question 3:
** Write a subroutine that will count the number of zeros that occur in a given linked list of `ints`. The subroutine should have a parameter of type ListNode and should return a value of type `int`.

[source, java]
----
class ListNode {
   int item;       // An item in the list.
   ListNode next;  // Pointer to next item in the list.
}
----

[source, java]
----
private static int countZeros(ListNode node) {
    int count = 0;
    ListNode explorer = node;
    while (explorer != null) {
        if (explorer.element == 0) {
            count++;
        }
        explorer = explorer.next;
    }

    return count;
}
----

---

* Question 4:
** Let `ListNode` be defined as in the previous problem. Suppose that head is a variable of type ListNode that points to the first node in a `linked lists`. 
** Write a code segment that will add `the number 42` in a new node at the end of the list. Assume that the list is not empty.

[source, java]
----
package quiz.unit_9;

public class Quiz4 {
    private static void insertNode(ListNode node) {
        ListNode newNode = new ListNode();
        newNode.element = 42;

        if (node.next == null) {
            node.next = newNode;
        } else {
            ListNode explorer = node;
            while (explorer.next != null) {
                explorer = explorer.next;
            }
            explorer.next = newNode;
            
        }
    }
}
----

---

* Question 5:
** List nodes can be used to build linked data structures that do not have the form of linked lists.
** Draw the data structure that is constructed by the code. What happens if you try to print the items in the data structure using the usual code for traversing a linked list

[source, java]
----
class ListNode {                     
    int item;                           
    ListNode next;                    
    Listnode(int i) {                 
        item = i;                       
        next = null;                    
    }                                  
}                                     
----

    ListNode one = new ListNode(10);
    ListNode two = new ListNode(20);
    ListNode three = new ListNode(30);
    ListNode four = new ListNode(40);
    one.next = two;
    two.next = three;
    three.next = four;
    four.next = two;

[source, java]
----
ListNode runner = one;
while (runner != null) {
    System.out.println(runner.item);
    runner = runner.next();
}
----

* 숫자 20, 30, 40이 영원히 반복해서 인쇄되는 무한 루프
---

* Question 6:
** What are the three operations on a stack?

1. push
2. pop
3. isEmpty

---

* Question 7:
** What is the basic difference between a stack and a queue?

* LIFO, FIFO의 차이?
---

* Question 8:
** What is an activation record? What role does a stack of activation records play in a computer?

---

* Question 9:
** Write a recursive subroutine that will find the sum of all the nodes in the tree. Your subroutine should have a parameter of type TreeNode, and it should return a value of type `int`.

[source, java]
----
class TreeNode {
   int item;       // One item in the tree.
   TreeNode left;  // Pointer to the left subtree.
   TreeNode right; // Pointer to the right subtree.
}
----

[source, java]
----
static int treeSum( TreeNode root ) {
    if ( root == null ) {
       return 0;
    }
    else {
       int total = root.item;
       total += treeSum(root.left);
       total += treeSum(root.right);
       return total;
    }
 }
----

---

* Question 10:
** Let  `TreeNode` be the same class as in the previous problem. Write a recursive subroutine that makes a copy of a binary tree. The subroutine has a parameter that points to the root of the tree that is to be copied. The return type is `TreeNode`, and the return value should be a pointer to the root of the copy. The copy should consist of newly created nodes, and it should have exactly the same structure as the original tree.

[source, java]
----
static TreeNode copyTree( TreeNode root ){
    if (root == null) {
        return null;
    }
    else {
         TreeNode rootOfCopy = new TreeNode();
         rootOfCopy.item = root.item;
         rootOfCopy.left = copyTree( root.left );
         rootOfCopy.right = copyTree( root.right );
         return rootOfCopy;
    }
}

----

---

* Question 11:
** What is a postorder traversal of a binary tree?

** 루트 노드를 제일 마지막에 탐색하는 방식으로 트리의 노드를 찾아간다.
---

* Question 12:
** Draw the binary sort tree that results. Then list the integers in the order that is produced by a post-order traversal of the tree.

    5   7   1   3   4   2   6

---

* Question 13:
** where a <word> can be any sequence of letters. Give five different <multilist>'s that can be generated by this rule. (This rule, by the way, is almost the entire syntax of the programming language LISP! LISP is known for its simple syntax and its elegant and powerful semantics.)

---

* Question 14:
** Explain what is meant by parsing a computer program.

* 문법 규칙을 사용하여 프로그램이 어떻게 구성될 수 있는지 알아내는 것을 의미합니다.