= Quiz on Chapter 2

* Question 1
** Briefly explain what is meant by the syntax and the semantics of a programming language. Give an example to illustrate the difference between a syntax error and a semantics error.

* 구문: 특정한 프로그래밍 언어를 작성하는 규칙, 이를 지키지 않는다면 컴파일 과정에서 오류가 발생하기 때문에 컴파일러가 해당 오류를 감지해준다.
* 의미: 구문에 맞게 프로그램을 구현하였으나, 구현한 내용 자체가 원래의 의도와 어긋나는 경우를 뜻한다.

---

* Question 2
** What does the computer do when it executes a variable declaration statement. Give an example.

* 컴퓨터는(정확히 CPU는) 변수를 선언할 때, 특정한 메모리의 위치에 값을 저장하고 그 저장한 위치의 값을 변수의 이름이라는 식별자로 호출 할 수 있도록 한다.

---

* Question 3
** What is a type, as this term relates to programming?

* 타입(Type)은 해당 변수 등에 사용될 수 있는, 저장될 수 있는 값들을 의미한다.

---

* Question 4
** One of the primitive types in Java is `boolean`. What is the `boolean` type? Where are `boolean` values used? What are its possible values?

* `boolean`은 true 혹은 false의 값을 가질 수 있는 타입이다. 이 타입은 주로 반복문, 조건문 등에서 반복을 지속할지, 어떠한 분기로 넘어가는지를 true 혹은 false의 값으로 예상되는 부분에서 사용됩니다.
---

* Question 5
** Give the meaning of each of the following Java operators:
*** `++`: 특정한 값에 1을 증가시킨다.
*** `&&`: 논리곱(and), 두 피연산자의 값이 모두 true라면 연산의 결과도 true를 보장하는 연산자이다.
*** `!=`: 두 피연산자가 같지 않다라는 의미로 두 피연산자가 다르다면 그 결과로 true를 반환한다.

---

* Question 6
** Explain what is meant by an assignment statement, and give an example. What are assignment statements used for?

* Assignment는 이미 값이 지정된 변수에 새로운 값을 넣어주는 것을 의미한다. 보통 반복문이나 조건문에서 기존의 값을 새로운 값으로 변경시킬 때 사용한다.
---

* Question 7
** What is meant by precedence of operators?

* 여러 연산들이 복잡하게 섞이는 경우, 우선순위 규칙이 없으면 1개의 표현식으로 다양한 결과가 도출되는데 이러한 경우에 연산자의 우선순위를 지정하여 해당 표현식의 일관된 결과를 도출하게끔 하는 규칙을 말한다.
* 어떠한 연산자가 먼저 실행되는지를 결정하는 방법

---

* Question 8
** What is a literal?

* 코드 내부에서 직접적으로 정의된 일종의 상수

---

* Question 9
** In Java, classes have two fundamentally different purposes. What are they?

* 정적 메서드, 정적 변수의 저장공간의 역할
* 실세계에서 존재하는 객체를 추상화한 설계, 상세의 역할

---

* Question 10
** What is the difference between the statement `x = TextIO.getDouble();` and the statement `x = TextIO.getlnDouble();`

* 두 명령문 모두 사용자가 입력한 실수를 읽고 해당 숫자를 변수 x에 저장합니다. 둘 다 정확히 동일한 값을 읽고 반환합니다. 차이점은 두 번째 명령문( getlnDouble 사용 )에서 값을 읽은 후 컴퓨터는 다음 캐리지 리턴까지 입력에서 문자를 계속 읽는다는 것입니다. 이러한 추가 문자는 삭제됩니다.

---

* Question 11
** Explain why the value of the expression `2 + 3 + "test"` is the string `"5test"` while the value of the expression `"test" + 2 + 3` is the string `"test23"`. What is the value of `"test" + 2 * 3` ?

* 문자열과의 `+` 연산을 하면 문자열로 타입이 변경된다. 덧셈을 할 때도 좌측에서부터 연산을 시작하기 때문에 문자열로 타입이 변환되기전에 산술연산을 한 후, 문자열로 변환되어 값이 다르다. 곱셉이 껴있다면, 연산자 우선순위에 의거하여 곱셉 연산을 우선으로 처리하고 그 다음에 문자열로 변환하는 작업을 수행한다.

---

* Question 12
** Integrated Development Environments such as Eclipse often use syntax coloring, which assigns various colors to the characters in a program to reflect the syntax of the language. 
** A student notices that Eclipse colors the word String differently from int, double, and `boolean`. The student asks why String should be a different color, since all these words are names of types. What's the answer to the student's question?

* 문자열은 Java의 기본 타입이 아닌, 클래스 타입(사용자가 정의, Java에서 기본적으로 구성된 클래스)라서 형식이 다르다.

---

* Question 13
** What is the purpose of an import directive, such as import textio.TextIO or import java.util.Scanner?

* 다른 파일이나 폴더에서 작성한 코드를 지금 작업 중인 파일에서 사용하기 위해서 해당 키워드를 사용한다.
---

* Question 14
** Write a complete program that asks the user to enter the number of "widgets" they want to buy and the cost per widget. The program should then output the total cost for all the widgets. Use System.out.printf to print the cost, with two digits after the decimal point. You do not need to include any comments in the program.

[source, java]
----
package exercise.unit_2;

import java.util.NoSuchElementException;
import java.util.Scanner;

public class Quiz {
    public static void main(String[] args) {

        try (Scanner scanner = new Scanner(System.in);) {

            int result = 0;
            int numbersOfWidgets = scanner.nextInt();
            for (int i = 0; i < numbersOfWidgets; i++) {
                result += scanner.nextInt();
            }

            System.out.println(result);
        } catch (NoSuchElementException e) {
            System.out.println(e.getMessage());
        }
    }
}
----