= Programming Exercises for Chapter 12

* Exercise 1
** Can you really get errors by using an unsynchronized counter with multiple threads? 
** Write a program to find out. Use the following unsynchronized counter class.

[source, java]
----
static class Counter {
    int count;
    void inc() {
        count = count+1;
    }
    int getCount() {
        return count;
    }
}
----

---

* Exercise 2
** write a program that uses multiple threads to solve the same problem, but for the range 1 to 100000. By using threads, your program will take less time to do the computation when it is run on a multiprocessor computer. At the end of the program, output the elapsed time, the integer that has the largest number of divisors, and the number of divisors that it has.

---

* Exercise 3
** Each thread in the pool runs in a loop in which it repeatedly takes a task from a queue and carries out that task. Implement a thread pool strategy for solving the same maximum-number-of-divisors problem as in the previous exercise.
** you should try a new technique for combining the results from all the tasks: Use two queues in your program. Use a queue of tasks, as usual, to hold the tasks that will be executed by the thread pool.
** the result from that task should be placed into the result queue. The main program can read results from the second queue as they become available, and combine all the results to get the final answer. The result queue will have to be a blocking queue.

---

* Exercise 4
** Write one more program to solve the problem, this time using an `ExecutorService` and `Futures`. 
** The program should still break up the computation into a fairly large number of fairly small tasks, and it should still print out the largest number of divisors and the integer that has that number of divisors.

---

* Exercise 5
** Modify the program to turn `Exercise 11.3` into a multithreaded server. Use a thread pool of connection-handling threads and use an `ArrayBlockingQueue` to get connected sockets from the `main()` routine to the threads.

---

* Exercise 6
** you should write a GUI program that does this computation and displays the result.
** The computation should be done in a separate thread, and the results should be displayed periodically. The program can use Labels to the display the results. It should set the text on the labels after running each batch of, say, one million trials.
** We can pick a random point in the square by choosing numbers x and y in the range 0 to 1 (using Math.random()). Since the equation of the circle is x*x+y*y=1, the point lies inside the circle if x*x+y*y is less than 1. One trial consists of picking x and y and testing whether x*x+y*y is less than 1. To get an estimate for π, you have to do many trials, count the trials, and count the number of trials in which x*x+y*y is less than 1,

[source, java]
----
for (int i = 0; i < BATCH_SIZE; i++) {
    double x = Math.random();
    double y = Math.random();
    trialCount++;
    if (x*x + y*y < 1)
        inCircleCount++;                        
}

double estimateForPi = 4 * ((double)inCircleCount / trialCount);
Platform.runLater( () -> {
    countLabel.setText(      " Number of Trials:   " + trialCount);
    piEstimateLabel.setText( " Current Estimate:   " + estimateForPi);
} );
----

---

* Exercise 7
** First, it would be nice if the participants in the chat room could be identified by name instead of by number. 
** Second, it would be nice if one person could send a private message to another person that would be seen just by that person rather than by everyone. Make these two changes. 
** You can start with a copy of the package netgame.chat. You will also need the package `netgame.common`, which defines the `netgame framework`.
